simplestore/cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.CartView.as_view(), name='index'),
    url(r'^add/(?P<product_id>[0-9]+)/$', views.AddToCartView.as_view(), name='add'),
    url(r'^remove/(?P<product_id>[0-9]+)/$', views.RemoveCartItemView.as_view(), name='remove'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.UpdateCartItemView.as_view(), name='update'),
]

simplestore/products/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^category/(?P<category_slug>[-\w\d]+)/$', views.CategoryDetailView.as_view(), name='category'),
    url(r'^(?P<slug>[-\w\d]+)/$', views.ProductDetailView.as_view(), name='detail'),
    url(r'^$', views.ProductsListView.as_view(), name='index')
]

simplestore/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^api/v1/', include('simplestore.api.urls', namespace='api')),
    url(r'^profiles/', include('simplestore.profiles.urls', namespace='profiles')),
    url(r'^cart/', include('simplestore.cart.urls', namespace='cart')),
    url(r'^checkout/', include('simplestore.checkout.urls', namespace='checkout')),
    url(r'^', include('simplestore.products.urls', namespace='products')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplestore/products/models/category.py
from django.db import models
from django.urls import reverse
from filer.fields.image import FilerImageField

class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    image = FilerImageField(null=True, blank=True)
    slug = models.SlugField(unique=True)

    _metadata = {
        'description': 'description',
    }

    class Meta:
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('products:index', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name

simplestore/products/models/product.py
from django.core.urlresolvers import reverse
from django.db import models
from filer.fields.image import FilerImageField

from .category import Category


class ProductQuerySet(models.QuerySet):
    def active(self):
        return self.filter(is_active=True)


class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self.db)

    def all(self):
        return self.get_queryset().active()


class Product(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    sku = models.CharField(
        max_length=50,
        verbose_name='Reference Number',
        unique=True
    )
    created_at = models.DateTimeField(auto_now=True, db_index=True)
    updated_at = models.DateTimeField(auto_now_add=True, db_index=True)
    image = FilerImageField(null=True, blank=True, on_delete=models.DO_NOTHING)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    perex = models.TextField(max_length=255)
    content = models.TextField(verbose_name='Content Description')
    category = models.ManyToManyField(Category, blank=True)
    is_active = models.BooleanField(default=True, verbose_name='Active')
    is_featured = models.BooleanField(default=False, verbose_name='Featured')

    objects = ProductManager()

    _metadata = {
        'description': 'content',
    }

    class Meta:
        ordering = ['-created_at']

    @property
    def get_image_url(self):
        return self.image.url

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name

simplestore/products/views.py
from django.views.generic import ListView, DetailView

from simplestore.cart.forms import AddToCartForm
from .models.product import Product, Category


class CategoryDetailView(DetailView):
    model = Category
    slug_url_kwarg = 'category_slug'
    template_name = "category_detail.html"

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)

        products = Product.objects.filter(
            category=self.get_object()
        ).prefetch_related('image')

        context.update({
            'products': products
        })
        return context


class ProductsListView(ListView):
    model = Product
    queryset = Product.objects.all().active().prefetch_related('image')
    template_name = "product_list.html"


class ProductDetailView(DetailView):
    model = Product
    template_name = "product_detail.html"

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['form'] = AddToCartForm
        return context

simplestore/products/templates/category_detail.html
{% extends "base.html" %}

{% load thumbnail %}

{% block content %}
  <div class="container">
    <div class="row products-row">
      <ul class="product-list full-width">
        {% for product in products %}
          <li class="product-list__item col-xs-6 col-md-4">
            <a href="{% url "products:detail" product.slug %}">
              {% if product.image %}
                <img class="b-lazy img-responsive full-w" data:image
                /gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
                data-src="{% thumbnail product.image 360x480 crop %}"
                alt="{{ product.name }}">
              {% endif %}
              <h2>{{ product.name }}</h2>
              <span class="product-list__item__price">${{ product.price }}</span>
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

simplestore/products/templates/product_detail.html
{% extends "base.html" %}

{% load thumbnail %}

{% block content %}
  <div class="container">
    <div class="row">
      <article class="product-detail">
        <section class="col-sm-12 col-md-5 col-md-push-1">
          <figure>
            <img class="img-responsive full-width" src="{% thumbnail object.image 460x690 crop %}" alt="">
          </figure>
        </section>
        <section class="col-sm-12 col-md-4 col-md-push-2">
          <hgroup class="product-detail-head">
            <h1>{{ object.name }}</h1>
            <h4 class="product-detail-head__price">${{ object.price|floatformat }}</h4>
          </hgroup>
          <p class="product-detail__desc">{{ object.content }}</p>
          <form method="post" action="{% url "cart:add" object.pk %}">
            {% csrf_token %}
            <div class="product-quantity">
              {{ form.quantity.errors }}
              <p>Quantity:</p>
              {{ form.quantity }}
            </div>
            <button type="submit" class="btn btn-default full-width btn-buy">
              <i class="fa fa-shopping-bag" aria-hidden="true"></i> &nbsp;Add to bag
            </button>
          </form>
        </section>
      </article>
    </div>
  </div>
{% endblock %}

simplestore/products/templates/product_list.html
{% extends "base.html" %}
{% load thumbnail %}

{% block content %}
  <div class="container">
    <div class="row products-row">
      <ul class="product-list">
        {% for object in object_list %}
          <li class="product-list__item col-xs-6 col-md-4">
            <a href="{% url "products:detail" object.slug %}">
              {% if object.image %}
                <img class="b-lazy img-responsive full-w"
                     src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                     data-src="{% thumbnail object.image 360x480 crop %}"
                     alt="{{ object.name }}">
              {% endif %}
              <h2>{{ object.name }}</h2>
              <span class="product-list__item__price">${{ object.price }}</span>
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}