simplestore/cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.CartView.as_view(), name='index'),
    url(r'^add/(?P<product_id>[0-9]+)/$', views.AddToCartView.as_view(), name='add'),
    url(r'^remove/(?P<product_id>[0-9]+)/$', views.RemoveCartItemView.as_view(), name='remove'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.UpdateCartItemView.as_view(), name='update'),
]

simplestore/products/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^category/(?P<category_slug>[-\w\d]+)/$', views.CategoryDetailView.as_view(), name='category'),
    url(r'^(?P<slug>[-\w\d]+)/$', views.ProductDetailView.as_view(), name='detail'),
    url(r'^$', views.ProductsListView.as_view(), name='index')
]

simplestore/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^api/v1/', include('simplestore.api.urls', namespace='api')),
    url(r'^profiles/', include('simplestore.profiles.urls', namespace='profiles')),
    url(r'^cart/', include('simplestore.cart.urls', namespace='cart')),
    url(r'^checkout/', include('simplestore.checkout.urls', namespace='checkout')),
    url(r'^', include('simplestore.products.urls', namespace='products')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplestore/cart/models.py
from django.conf import settings
from django.db import models

from simplestore.products.models.product import Product


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    session_key = models.CharField(max_length=255, null=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)
    price_subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=0, null=True)
    price_total = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    class Meta:
        unique_together = ('user', 'session_key')

    def update_subtotal(self):
        subtotal = self.items.all().aggregate(sum=models.Sum('total_price'))
        self.price_subtotal = subtotal['sum']
        self.save()

    def get_total_quantity_of_items(self):
        qty = self.items.all().aggregate(sum=models.Sum('quantity'))
        return qty['sum']

    def __str__(self):
        return "Cart id: {id}".format(id=self.pk)


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, null=True, related_name='items', blank=True)
    product = models.ForeignKey(Product, related_name='products', on_delete=models.DO_NOTHING)
    date_added = models.DateTimeField(auto_now_add=True)
    quantity = models.PositiveIntegerField(default=1)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, null=True)

    class Meta:
        ordering = ['date_added']

    def get_absolute_url(self):
        return self.product.get_absolute_url()

    def __str__(self):
        return self.product.name

simplestore/cart/forms.py
from django import forms
from .models import CartItem


class AddToCartForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = [
            'quantity'
        ]
        widgets = {
            'quantity': forms.NumberInput(attrs={'class': 'full-width'})
        }

simplestore/cart/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import DeleteView, FormView, TemplateView

from simplestore.products.models.product import Product
from .forms import AddToCartForm
from .models import CartItem
from .utils import get_cart


class CartView(TemplateView):
    template_name = "cart_index.html"

    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)

        cart = get_cart(self.request)

        items = []
        if cart:
            items = cart.items.select_related('product__image')

        context.update({
            'cart': cart,
            'cart_items': items
        })

        return context


# Removing item from cart
class RemoveCartItemView(DeleteView):
    model = CartItem
    success_url = reverse_lazy('cart:index')
    success_message = "The item has been deleted from your cart."
    http_method_names = ['post']

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(RemoveCartItemView, self).delete(self.request, *args, **kwargs)

    def get_object(self, *args, **kwargs):
        cart = get_cart(self.request)
        return CartItem.objects.get(cart=cart, product_id=self.kwargs['product_id'])


class UpdateCartItemView(FormView):
    http_method_names = ['post']
    success_url = reverse_lazy('cart:index')
    form_class = AddToCartForm
    template_name = 'cart_index.html'
    context_object_name = 'cart'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        cart = get_cart(request)
        cart_item = CartItem.objects.get(cart=cart, pk=self.kwargs['pk'])
        cart_item.quantity = request.POST['cart_item_quantity']
        cart_item.save()
        return self.form_valid(form)

    def form_valid(self, form, *args, **kwargs):
        messages.success(self.request, "Product quantity has been updated.")
        return super(UpdateCartItemView, self).form_valid(form)


class AddToCartView(FormView):
    template_name = 'product_detail.html'
    success_url = reverse_lazy('cart:index')
    http_method_names = ['post']
    form_class = AddToCartForm

    def form_valid(self, form, *args, **kwargs):
        product = get_object_or_404(Product, pk=self.kwargs['product_id'])
        quantity = form.cleaned_data['quantity']

        cart = get_cart(self.request, create=True)
        cart_item, cart_item_created = CartItem.objects.update_or_create(cart=cart, product=product)

        # If Cart item object has not been created  , amend quantity.
        if cart_item_created is False:
            cart_item.quantity += quantity
        else:
            cart_item.quantity = quantity

        cart_item.save()

        return super(AddToCartView, self).form_valid(form)

simplestore/cart/templates/cart_counter.html
<a href="{% url "cart:index" %}">
  <span class="visible-xs-inline">Shopping bag</span>
  <i class="fa fa-shopping-bag" aria-hidden="true"></i>
  <span class="bag-count"> {{ cart_items_total_qty }}</span>
</a>

simplestore/cart/templates/cart_empty.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h2>Shopping Cart</h2>
        <p> Your Shopping Cart is empty </p>
        <a href="{% url "products:index" %}" class="btn btn-primary">Go Shopping!</a>
      </div>
    </div>
  </div>
{% endblock %}

simplestore/cart/templates/cart_index.html
{% extends "base.html" %}

{% load thumbnail %}

{% block content %}

  {% if cart_items %}
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <h1>Shopping Cart</h1>

          <table id="cart" class="table table-hover table-condensed">
            <thead>
            <tr>
              <th style="width:30%">Product</th>
              <th style="width:10%">Price</th>
              <th style="width:8%">Quantity</th>
              <th style="width:22%" class="text-center">Subtotal</th>
              <th style="width:10%"></th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
              <tr>
                <td data-th="Product">
                  <div class="row">
                    <div class="col-sm-2 hidden-xs">
                      <a href="{% url "products:detail" cart_item.product.slug %}"><img
                          class="img-responsive"
                          src="{% thumbnail cart_item.product.image 100x100 crop %}"
                          alt=""></a>
                    </div>
                    <div class="col-sm-10">
                      <h4 class="nomargin">{{ cart_item.product.name }}</h4>
                      <p>{{ cart_item.product.perex }}</p>
                    </div>
                  </div>
                </td>
                <td data-th="Price">${{ cart_item.product.price|floatformat }}</td>
                <td data-th="Quantity">
                  <form action="{% url "cart:update" cart_item.id %}" method="post">
                    {% csrf_token %}
                    <input class="cart_item_quantity" type="number" name="cart_item_quantity" min="1"
                           value="{{ cart_item.quantity }}">
                    <button type="submit" class="btn btn-info btn-sm"><i class="fa fa-refresh"></i>
                    </button>
                  </form>
                </td>
                <td data-th="Subtotal" class="text-center">${{ cart_item.total_price|floatformat }}</td>
                <td class="actions" data-th="">
                  <form action="{% url "cart:remove" cart_item.product.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm"><i
                        class="fa fa-trash-o"></i></button>
                  </form>
                </td>
              </tr>
            {% endfor %}
            </tbody>

            <tfoot>
            <tr class="visible-xs">
              <td class="text-center"><strong>Total ${{ cart.price_subtotal|floatformat }}</strong></td>
            </tr>
            <tr>
              <td><a href="/" class="btn btn-default">Continue
                Shopping</a></td>
              <td colspan="2" class="hidden-xs"></td>
              <td class="hidden-xs text-center"><strong>Total
                ${{ cart.price_subtotal|floatformat }}</strong></td>
              <td><a href="{% url "checkout:index" %}" class="btn btn-primary btn-block">Checkout </a>
              </td>
            </tr>
            </tfoot>
          </table>

        </div>
      </div>
    </div>

  {% else %}

    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <h2>Shopping Cart</h2>
          <p> Your Shopping Cart is empty </p>
          <a href="{% url "products:index" %}" class="btn btn-primary">Go Shopping!</a>
        </div>
      </div>
    </div>

  {% endif %}

{% endblock %}