simplestore/profiles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^register/', views.RegistrationFormView.as_view(), name='register'),
    url(r'^orders/$', views.ProfileOrdersView.as_view(), name='orders'),
    url(r'^orders/(?P<pk>\d+)/$', views.ProfileOrderDetailView.as_view(), name='order_detail'),
    url(r'^login/', views.AuthenticationForm.as_view(), name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^profile/$', views.ProfileDetail.as_view(), name='detail'),
    url(r'^profile/update/$', views.UpdateProfileForm.as_view(), name='update'),
]

simplestore/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^api/v1/', include('simplestore.api.urls', namespace='api')),
    url(r'^profiles/', include('simplestore.profiles.urls', namespace='profiles')),
    url(r'^cart/', include('simplestore.cart.urls', namespace='cart')),
    url(r'^checkout/', include('simplestore.checkout.urls', namespace='checkout')),
    url(r'^', include('simplestore.products.urls', namespace='products')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplestore/profiles/models.py
import uuid

from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.db import models


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save()

        return user

    def create_superuser(self, email, password=None, **kwargs):
        superuser = self.create_user(email, password, **kwargs)
        superuser.is_admin = True
        superuser.is_staff = True
        superuser.is_superuser = True
        superuser.save()

        return superuser


class Profile(AbstractBaseUser, PermissionsMixin):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    email = models.EmailField(blank=False, unique=True)
    created = models.DateField(auto_now_add=True)
    name = models.CharField(max_length=100, blank=False)
    surname = models.CharField(
        max_length=100,
        blank=False,
        verbose_name="Last Name"
    )
    slug = models.SlugField(blank=False)
    updated = models.DateField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    website = models.URLField(blank=True)
    about = models.TextField(blank=True)

    USERNAME_FIELD = 'email'

    objects = CustomUserManager()

    def get_short_name(self):
        return self.name

    def get_full_name(self):
        return '{0} {1}'.format(self.name, self.surname)

    def __str__(self):
        return self.email

simplestore/profiles/forms.py
from django import forms

from .models import Profile


class RegistrationForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.widgets.EmailInput)

    password1 = forms.CharField(
        widget=forms.PasswordInput(),
        label="Password",
        min_length=8
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(),
        label="Password confirmation",
        min_length=8
    )

    class Meta:
        model = Profile
        fields = ['name', 'surname', 'email', 'password1', 'password2']

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("Passwords do not match")
        return self.cleaned_data

    def save(self, commit=True):
        profile = super(RegistrationForm, self).save(commit=False)
        profile.set_password(self.cleaned_data['password1'])
        if commit:
            profile.save()
        return profile


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.widgets.EmailInput)
    password = forms.CharField(widget=forms.PasswordInput(), label="Password")

    class Meta:
        fields = ['email', 'password']

simplestore/profiles/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormView, UpdateView

from simplestore.cart.utils import get_cart
from simplestore.checkout.models.order import Order
from .forms import RegistrationForm, LoginForm
from .models import Profile


def profile_index(request):
    return render(request, "profile_index.html")


# Profile Detail
class ProfileDetail(LoginRequiredMixin, DetailView):
    template_name = "profile_detail.html"
    login_url = reverse_lazy('profiles:login')
    model = Profile

    def get_object(self, queryset=None):
        return Profile.objects.get(pk=self.request.user.pk)


# Registration Form
class RegistrationFormView(FormView):
    template_name = "profile_register.html"
    form_class = RegistrationForm
    success_url = reverse_lazy('products:index')

    def form_valid(self, form):
        self.profile = form.save()
        self.request.session['user_cart'] = self.request.session.session_key

        user = authenticate(
            email=self.profile.email,
            password=self.request.POST['password1']
        )

        messages.add_message(
            self.request, messages.SUCCESS,
            'You were successfully logged in.'
        )

        login(self.request, user)
        return super(RegistrationFormView, self).form_valid(form)


class UpdateProfileForm(LoginRequiredMixin, UpdateView):
    template_name = 'profile_update.html'
    form_class = RegistrationForm
    model = Profile
    success_url = reverse_lazy('homepage')
    login_url = reverse_lazy('profiles:login')

    def get_object(self, queryset=None):
        return Profile.objects.get(pk=self.request.user.pk)


class ProfileOrdersView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'profile_orders.html'
    login_url = reverse_lazy('profiles:login')

    def get_context_data(self, **kwargs):
        context = super(ProfileOrdersView, self).get_context_data(**kwargs)
        context['orders'] = Order.objects.filter(user=self.request.user.id)

        return context


class ProfileOrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'profile_order_detail.html'
    login_url = reverse_lazy('profiles:login')


# Login
class AuthenticationForm(FormView):
    template_name = 'profile_login.html'
    form_class = LoginForm
    success_url = reverse_lazy('products:index')

    def form_valid(self, form):

        cart = get_cart(self.request, create=True)
        user = authenticate(email=self.request.POST['email'], password=self.request.POST['password'])

        if user is not None and user.is_active:
            self.request.session['user_cart'] = self.request.session.session_key
            login(self.request, user)

            if cart is not None:
                cart.user = Profile.objects.get(id=user.id)
                cart.save()
                messages.add_message(self.request, messages.SUCCESS, 'You were successfully logged in.')

            return super(AuthenticationForm, self).form_valid(form)

        else:
            response = super(AuthenticationForm, self).form_invalid(form)
            messages.add_message(self.request, messages.WARNING, 'Wrong email or password. Please try again')
            return response


# Logout View
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

simplestore/profiles/templates/profile_detail.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-3">
        <ul class="list-group side-nav">
          <li class="list-group-item"><a href="">Edit details</a></li>
          <li class="list-group-item"><a href="{% url "profiles:orders" %}">Orders</a></li>
          <li class="list-group-item"><a href="">Change password</a></li>
        </ul>
      </div>
      <div class="col-sm-12 col-md-8 pull-right">
        <h2>{{ object.get_full_name }}</h2>
        <p><strong>Email:</strong> {{ object.email }}</p>
        <a class="btn btn-primary" href="{% url 'profiles:update' %}">Edit details</a>
        <a class="btn btn-danger" href="{% url 'profiles:logout' %}">Logout</a>
      </div>
    </div>
  </div>
{% endblock %}

simplestore/profiles/templates/profile_index.html
{% extends "base.html" %}

{% block content %}
  heloo
{% endblock %}

simplestore/profiles/templates/profile_login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-4 col-md-push-4">
        <h2 class="text-center">Sign In</h2>
        <form action="{{ request.path }}" method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-primary btn-block">Sign in</button>
        </form>
        <br/>
        <p class="text-center">Don't have an account?<a href="{% url "profiles:register" %}"> Sign up</a></p>
      </div>
    </div>
  </div>
  {#    <a href="{% url 'social:begin' 'instagram' %}?next=/">Login with Instagram</a>#}
  {#    <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>#}
  {#    <a href="{% url 'social:begin' 'google-oauth2' %}?next=/">Login with Google</a>#}
{% endblock %}

simplestore/profiles/templates/profile_order_detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>Order #{{ order.id }}</h1>
        <p>
          <strong>Status: </strong>{{ order.status|capfirst }} </br>
          <strong>Created at: </strong>{{ order.created_at }} </br>
          <strong>Delivery type: </strong> {{ order.delivery_method }}
        </p>
        <h3>Order details</h3>
        <table class="table table-responsive vertical-middle">
          <tr>
            <th>Image</th>
            <th>Product name</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Price total</th>
          </tr>
          {% for item in order.items.all %}
            <tr>
              <td>
                <a href="{% url "products:detail" item.product.slug %}">
                  <img
                      class="img-responsive"
                      src="{% thumbnail item.product.image 50x50 crop %}"
                      alt="{{ item.product.name }}"/>
                </a>
              </td>
              <td>{{ item.product.name }}</td>
              <td>{{ item.quantity }}</td>
              <td>{{ item.price }}</td>
              <td>{{ item.total_price }}</td>
            </tr>
          {% endfor %}
        </table>

      </div>
    </div>
  </div>
{% endblock %}

simplestore/profiles/templates/profile_orders.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>Orders</h1>
        {% if orders %}
          <table class="table table-responsive">
            <thead>
            <tr>
              <th>Id</th>
              <th>Created at</th>
              <th>Delivery method</th>
              <th>Payment method</th>
              <th>Total</th>
              <th>&nbsp;</th>
            </tr>
            </thead>
            {% for order in orders %}
              <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.created_at }}</td>
                <td>{{ order.delivery_method }}</td>
                <td>{{ order.payment_method }}</td>
                <td>total price</td>
                <td><a href="{% url "profiles:order_detail" pk=order.id %}">View more</a></td>
              </tr>
            {% endfor %}
          </table>
        {% else %}
          <p>You haven't created any orders.</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

simplestore/profiles/templates/profile_register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-4 col-md-push-4">
        <h2 class="text-center">Create your account</h2>
        <form class="form" action="{{ request.path }}" method="post">
          {{ form|crispy }}
          <button type="submit" class="btn btn-primary btn-block">Submit</button>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

simplestore/profiles/templates/profile_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-3">
        <ul class="list-group side-nav">
          <li class="list-group-item"><a href="">Edit details</a></li>
          <li class="list-group-item"><a href="{% url "profiles:orders" %}">Orders</a></li>
        </ul>
      </div>
      <div class="col-sm-12 col-md-6 col-md-push-1">
        <h2>Edit details</h2>
        <form action="{{ request.path }}">
          {{ form|crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>

{% endblock %}